const User=require('../models/userModel');const Project=require('../models/projectModel');const SocialLink=require('../models/socialLinkModel');
async function dashboard(req,res){try{const user=await User.getById(req.session.user.id);const projects=await Project.getByUserId(req.session.user.id);const socialLinks=await SocialLink.getByUserId(req.session.user.id);res.render('dashboard',{title:`Dashboard for ${user.username}`,user,projects,socialLinks});}catch(e){renderError(res,e);}}
async function updateProfile(req,res){try{const{bio,email,photo}=req.body;if(email&&email.trim()){await User.updateProfile(req.session.user.id,{bio:bio||'',email:email.trim(),photo:photo||''});req.session.user.email=email.trim();}res.redirect('/dashboard');}catch(e){renderError(res,e);}}
async function addSocialLink(req,res){try{const{platform,url}=req.body;if(platform&&url){await SocialLink.create(req.session.user.id,{platform:platform.trim(),url:url.trim()});}res.redirect('/dashboard');}catch(e){renderError(res,e);}}
async function deleteSocialLink(req,res){try{await SocialLink.remove(req.params.id,req.session.user.id);res.redirect('/dashboard');}catch(e){renderError(res,e);}}
async function addProject(req,res){try{const{title,description,repo_url,live_url}=req.body;if(title&&description){await Project.create(req.session.user.id,{title:title.trim(),description:description.trim(),repo_url:repo_url?repo_url.trim():'',live_url:live_url?live_url.trim():''});}res.redirect('/dashboard');}catch(e){renderError(res,e);}}
async function showEditProject(req,res){try{const project=await Project.getByIdAndUserId(req.params.id,req.session.user.id);if(!project){return res.status(404).render('error',{title:'Proyecto no encontrado',message:'No puedes editar este proyecto o no existe.'});}res.render('project-form',{title:'Edit Project',project});}catch(e){renderError(res,e);}}
async function updateProject(req,res){try{const{title,description,repo_url,live_url}=req.body;await Project.update(req.params.id,req.session.user.id,{title:title?title.trim():'',description:description?description.trim():'',repo_url:repo_url?repo_url.trim():'',live_url:live_url?live_url.trim():''});res.redirect('/dashboard');}catch(e){renderError(res,e);}}
async function deleteProject(req,res){try{await Project.remove(req.params.id,req.session.user.id);res.redirect('/dashboard');}catch(e){renderError(res,e);}}
function renderError(res,e){console.error(e);res.status(500).render('error',{title:'Error interno',message:'Ha ocurrido un error al procesar la operación.'});}
module.exports={dashboard,updateProfile,addSocialLink,deleteSocialLink,addProject,showEditProject,updateProject,deleteProject};
