DROP DATABASE IF EXISTS devportfolio;
CREATE DATABASE devportfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE devportfolio;
CREATE TABLE users (id INTEGER PRIMARY KEY AUTO_INCREMENT,username VARCHAR(100) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,bio TEXT,email VARCHAR(255) UNIQUE NOT NULL,photo VARCHAR(500));
CREATE TABLE projects (id INTEGER PRIMARY KEY AUTO_INCREMENT,title VARCHAR(255) NOT NULL,description TEXT,repo_url VARCHAR(500),live_url VARCHAR(500),user_id INTEGER NOT NULL,CONSTRAINT fk_projects_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE social_links (id INTEGER PRIMARY KEY AUTO_INCREMENT,platform VARCHAR(100) NOT NULL,url VARCHAR(500) NOT NULL,user_id INTEGER NOT NULL,CONSTRAINT fk_social_links_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
